services:
  twitch-bot:
    build:
      context: .
      dockerfile: dockerfile-twitch
    image: c2s-bot:latest
    container_name: c2s-bot
    env_file:
      - .env
    volumes:
      - ./twitch/config.json:/app/config.json
    restart: unless-stopped
