FROM python:3.12-slim AS builder

WORKDIR /install

RUN pip install --upgrade pip setuptools wheel

COPY requirements.txt .

RUN pip install --no-cache-dir --prefix=/install/deps -r requirements.txt

FROM python:3.12-slim AS final

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY --from=builder /install/deps /usr/local

COPY bot-discord.py .

CMD ["python", "bot-discord.py"]